### ISSUE TITLE
Jade Cocoon french name issue

### ISSUE THREAD

**Issue by andiandi13** [libretro-thumbnails/Sony_-_PlayStation#157]
The game should be named "Jade Cocoon - La Légende De Tamamayu (France)" instead of "Jade Cocoon - Story of the Tamamayu (France)".

Also, in the thumbnails, there's "Jade Cocoon - La Légende De Tamamayu (Europe)" (with the french name). I think that make no sense since it released elsewhere like in Germany and that name can't be found on the RA database.

**Comment by andiandi13** [comment]
Never mind I think accents are not good and make games crash

**Comment by i30817** [comment]
@andiandi13 , the way libretro playlists works, is that playlists have a 'path' and a 'label'. The path is restricted to the 'minimal common denominator' which in this case is windows forbidden characters. The label is utf-8 (i think) and can display anything.

There is actually no real reason why accents couldn't be in filenames i believe, except that they play badly with the naive charsets in the html of pages or people not uploading utf-8 filenames.

**Comment by i30817** [comment]
BTW, we're following the redump names.

http://redump.org/discs/quicksearch/jade-cocoon/

As you can see, the only french flag is marked with a english name.
