### ISSUE TITLE
Some how we did introduce some dupplicates items

### ISSUE THREAD

**Issue by MarcoEstevez** [libretro-thumbnails/Sony_-_PlayStation#41]
![image](https://user-images.githubusercontent.com/3447089/56507139-adc15c00-6520-11e9-8063-6a4c8b449651.png)

Syncing repository was not working for me until I realized some differences on names word cases that was not making windows specially happy

I can fix it, but what case would you like to keep? since it seems to be dupplicated at database level too

**Comment by RobLoach** [comment]
Ah, duplicates in the DB... Likely old ones.

**Comment by RobLoach** [comment]
Title case preferred.

**Comment by MarcoEstevez** [comment]
Great, thanks, I'll fix all ocurrences I found

**Comment by RobLoach** [comment]
Redump has the canonical titles:
http://redump.org/disc/7336/

Not sure where the duplicates come from:
https://github.com/libretro/libretro-database/search?q=ghost+in+the+shell&unscoped_q=ghost+in+the+shell

Do you know?

**Comment by MarcoEstevez** [comment]
I saw these in libretro-thumbnails-check list

https://raw.githubusercontent.com/RobLoach/libretro-thumbnails-check/master/out/Sony%20-%20PlayStation.txt

But not sure if this report comes from database you pointed out  :-)

![image](https://user-images.githubusercontent.com/3447089/56636118-123b0300-6668-11e9-8f08-304f355040a8.png)

**Comment by MarcoEstevez** [comment]
this particular example came from this commit https://github.com/libretro-thumbnails/Sony_-_PlayStation/commit/6e8c4bfca3e36e7f4017ee5437d103ca55bf8da7

**Comment by osirase** [comment]
Oh that was my bad. Ghost in the shell doesn't detect this thumbnail unless it's lower case on linux.

**Comment by osirase** [comment]
https://i.imgur.com/UDdw4ho.jpg Here's an example, it's only showing the thumbnail because my 'Ghost in the shell (Europe).png was manually put there by me.

**Comment by MarcoEstevez** [comment]
Unmmmm...

Looking at Retroarch --> info --> DatabaseManager --> Sony - Playstation.rdb, it has lower cases, that might be the reason why does not show them in Linux

![image](https://user-images.githubusercontent.com/3447089/56685876-31bb4580-66d3-11e9-9668-6093b30ea8e8.png)

**Comment by RobLoach** [comment]
So strange. Have no clue where those entries are coming from.

**Comment by cjoyau** [comment]
Just realized I introduced a duplicate for Driver - You're the wheelman (Europe).png yesterday. Seems like it should be lowercase based on https://raw.githubusercontent.com/RobLoach/libretro-thumbnails-check/master/out/Sony%20-%20PlayStation.txt

**Comment by RobLoach** [comment]
Ah, it's from PSXDataCenter:

- https://psxdatacenter.com/games/P/D/SLES-01978.html
- https://psxdatacenter.com/games/P/D/SLES-01977.html
- https://psxdatacenter.com/games/P/D/SLES-01976.html
- https://psxdatacenter.com/games/P/D/SLES-01975.html
- https://psxdatacenter.com/games/P/D/SLES-01816.html

**Comment by utajum** [comment]
Well if we all used only the serial numbers, life would be a lot simpler.

In libretro dat:
`007 - Tomorrow never dies (USA)`
`X-Men vs Street Fighter (USA)`

In Redump dat:
`007 - Tomorrow Never Dies (USA)`
`X-Men vs. Street Fighter (USA)`

There are more examples. In one dat 2 Disc's in other just one, etc.

My observation was that the images are loaded in RetroArch based on the filename. Although I'm not sure of this.

So if there are subtle differences between psxdatacenter, libretro and redump I think that duplicates should be allowed, or maybe Redump's dat should be given precedence since it is the content vs images only from psxdatacenter, but I have no idea what the goals are of this project, I just pop up every two years :)

Also since NTFS does not care about casing, problems will arise in Linux only.

**Comment by utajum** [comment]
So `retroarch/database/rdb/Sony - PlayStation.rdb` uses the same naming scheme as Redump's dat (sorry if this is obvious im clueless) in version 1.7.7

I also see that `Sony - PlayStation.rdb` was updated to conform with the naming scheme from psxdatacenter. 
Does this mean that redump titles will stop showing images or something?

**Comment by osirase** [comment]
Currently I manually rename the case sensitive png's that don't match on my Linux box. It's not that big of a deal but I do look forward to no longer depending on psxdatacenter I tried to email them about case sensitivety but got no response so it could be good not to rely on them.

**Comment by RobLoach** [comment]
Agreed. Redump does provide the Serials, but not in the DAT files themselves. We'll need to put together a scrapper for each page over here:
http://redump.org/discs/system/psx/

Would be awesome to have it do something similar for the other systems too.
