### ISSUE TITLE
Changes to Arc the Lad Collection names

### ISSUE THREAD

**Issue by deusX1** [libretro-thumbnails/Sony_-_PlayStation#94]
Hi,
I propose to change the current names for "Arc the Lad Collection" (Boxarts, Snaps, Titles) in order to follow the NoIntro / Redump name convention for this game.

For example, current Boxarts names for this compilation (it's on 6 CDs) are:
- Arc the Lad Collection (USA) (Disc 1 of 6)
- Arc the Lad Collection (USA) (Disc 2 of 6)
- Arc the Lad Collection (USA) (Disc 3 of 6)
- Arc the Lad Collection (USA) (Disc 4 of 6)
- Arc the Lad Collection (USA) (Disc 5 of 6)
- Arc the Lad Collection (USA) (Disc 6 of 6)

While NoIntro/Redump cd names are:
- Arc the Lad Collection - Arc the Lad (USA)
- Arc the Lad Collection - Arc the Lad II (USA)
- Arc the Lad Collection - Arc the Lad III (USA) (Disc 1)
- Arc the Lad Collection - Arc the Lad III (USA) (Disc 2)
- Arc the Lad Collection - Arc Arena - Monster Tournament (USA)
- Arc the Lad Collection - The Making of Arc the Lad (USA)

**Comment by i30817** [comment]
This happens a lot, one change will do almost nothing.

**Comment by RobLoach** [comment]
While it happens a lot, cleaning it up is the only way to fix it in the long term. Keep a positive attitude towards contributions. Thanks!
